### ISSUE TITLE
RPMsg TTY demo not working on the latest "sumo-imx-4.14.78-var01" branch

### ISSUE THREAD

**Issue by jdinh1** [varigit/meta-variscite-mx6#10]
Hi,

I'm having trouble getting the RPMsg TTY and RPMsg Ping Pong demo to work on the latest commit of `sumo-imx-4.14.78-var01`. It was still working on [this commit](https://github.com/varigit/meta-variscite-imx/tree/bf040dd48a653f542ccac069650f9e90d7eb4da6) . Can someone verify this isn't just me?

Tested on the DART-MX8M dev board

Thank you,
Jonathan

**Comment by varigigi** [comment]
Hi Jonathan,
thanks for reporting.
We are aware of the problem and its origin: we are already working on it.
For a faster technical support and further updates, please use the Variscite Customer Portal:
   http://varisciteportal.axosoft.com/
Anyway, I will take this issue open until fixed.
Best Regards
Pier

**Comment by varigigi** [comment]
Hi Jonathan,
sorry for the long delay, but we had to rework uboot, kernel and freertos sources to
- fix rpmsg communication
- move rpmsg area at address to allow using it for all RAM sizes
- move the M4 reserved memory in a  range accessible for all SoMs with 1 GB of RAM or more.
Please align your sources to latest commits.
In case of further support please contact us using the customer portal:
   http://varisciteportal.axosoft.com
Thanks
Best Regards
Pier
