### ISSUE TITLE
Update to thud or warrior

### ISSUE THREAD

**Issue by vicgal** [varigit/meta-variscite-mx6#11]
Hi,

Do you plan to update this layer to thud or warrior in the future? Could you please provide an estimated date for this?

Regards

**Comment by eranmati** [comment]
Hi.
This layer follows official NXP GA releases.
NXP's next GA release (warrior) is scheduled for November.
Shortly after it will be out we will also update our layer.

For future questions please open a ticket in Variscite's customer portal:
https://varisciteportal.axosoft.com

Regards,
Eran
