### ISSUE TITLE
BSPDIR reference inside var-image-swupdate.bb

### ISSUE THREAD

**Issue by rapgenic** [varigit/meta-variscite-mx6#12]
This issue is relative to the branch zeus-imx-5.4.24-var01.

In the var-image-swupdate.bb recipe, there is a reference to the BSPDIR variable:

https://github.com/varigit/meta-variscite-imx/blob/92a81a0a4144b8d6f7c9a17fb09472c89582823b/recipes-fsl/images/var-image-swupdate.bb#L8-L12

This is quite problematic when the layers are arranged in a different structure (which is our case): suddenly the path is not valid anymore and even if the recipe is not used an error prevents bitbake from compiling.

The issue should be easily resolved by replacing the line with:

```
require recipes-fsl/images/fsl-image-gui.bb 
```

Which works the same way except that it does not use an absolute path, so it works wherever the layer is.

Thank you,
Giulio

**Comment by nsdrude** [comment]
@rapgenic thank you for the recommendation, I have pushed a patch to address this: https://github.com/varigit/meta-variscite-imx/commit/3682c7976807de6e5376c44db911ed411cbdfc17

Thanks,
Nate
