### ISSUE TITLE
zeus-imx-5.4.24-var01 branch contains kernel which lacks dtb for imx8mm-var-dart

### ISSUE THREAD

**Issue by floion** [varigit/meta-variscite-mx6#13]
Hi, looking at the `zeus-imx-5.4.24-var01` branch, it seems that it uses kernel branch `imx_5.4.24_2.1.0_var01` which does not have the device tree for the imx8mm-var-dart. Can you update that kernel branch with the correct dtbs for the imx8mm-var-dart machine?

On a related note, I see there is an even newer kernel, `imx_5.4.47_2.2.0_var01`. Can this be used for the imx8mm-var-dart? This one is also missing the device tree for this hardware.

Thanks

**Comment by david-sterling** [comment]
Hi! As quick workaround you can build kernel with the Debian script from this git https://github.com/varigit/debian-var/tree/debian_bullseye_var01 since kernel is the same. When you build first time you will have dts code. 

Also you can reverse recovery SD dtb to dts.

Anyway I am sure Variscite team will push the dts soon, they are very nice guys :P 

Best, David

**Comment by floion** [comment]
Hi @david-sterling yeah there are ways I can fix this but I'd like to have the device tree in the kernel source so that I don't add up patches in our upstream layers.
Thanks for the input

**Comment by eranmati** [comment]
Hi @floion & @david-sterling.
We are currently working on Yocto Dunfell with a new kernel branch.
To see the official Yocto releases for each SOM see https://variwiki.com, or the release notes at https://github.com/varigit/variscite-bsp-platform/releases.

Regards,
Eran

**Comment by floion** [comment]
Oh no! It means that the zeus releases for the boards you support are scattered through various different branches? Why is that? Why can't there be just 1 zeus release branch in which all the boards you support are ok?

**Comment by floion** [comment]
This breaks everything in the yocto world and will force us to create yet another distinct repo for each machine you support. And this will lead to code duplication and useless extra effort.

**Comment by eranmati** [comment]
This repository follows NXP's official releases.
NXP released a few different releases based on Yocto Zeus and maintained a few different branches accordingly.
Ideally, we would officially support all SOMs on all of these releases, but some of them were not GA releases for all SOCs and some we just weren't quick enough to port and test on all of our SOMs (note that we are supporting all of NXP's i.MX8 family of SOCs, currently on 9 different SOMs, and 5 different OSes for each, on top of the previous SOM families).

https://github.com/varigit/meta-variscite-fslc follows the fsl-community releases and has one branch per Yocto release.
Yocto Dunfell will be based on the fsl-community and we are looking into releasing it for all of our i.MX based SOMs.

Until now we followed NXP's official releases for all of the i.MX8 family based SOMs, as we feel it's the best approach for newly released SOCs.
Now that the SOCs are more mature we are looking into making fsl-community based Yocto releases for our iMX8 based SOMs (aside from the SOMs based on the brand new i.MX8M-Plus SOC, which still has better support in NXP's official releases, for now).
The fact that Dunfell is LTS, and that NXP skipped it also helped us taking the jump in this particular point in time.
This was the same process we had with our i.MX6/6UL and i.MX7 based SOMs.

If you need help with consolidating the Zeus branches, you can open a ticket in the Variscite customer portal:
https://varisciteportal.axosoft.com

**Comment by floion** [comment]
Understood, thanks for the detailed answer. Guess we're all depending on what nxp releases so we need to make do.
