### ISSUE TITLE
Dunfell support

### ISSUE THREAD

**Issue by floion** [varigit/meta-variscite-mx6#14]
Hi, are you planning to release support for Yocto Dunfell?

Thank you

**Comment by eranmati** [comment]
Hi @floion.
Yes, we are working on Yocto Dunfell for all of our i.MX based SOMs.
The support will be added to https://github.com/varigit/meta-variscite-fslc, though, and not to this repository.
This repository follows NXP's official releases and meta-variscite-fslc follows the fsl-community releases.

You should follow https://github.com/varigit/variscite-bsp-platform and https://variwiki.com for new releases.

Regards,
Eran

**Comment by floion** [comment]
So what is the approach to use? Which layer should be used to be up-to-date? This layer or `meta-variscite-fslc` ? I'm a little confused
Thanks for the quick answer

**Comment by eranmati** [comment]
As I wrote, you should follow https://variwiki.com and/or https://github.com/varigit/variscite-bsp-platform/releases.
In variwiki.com you will find full release notes, build instructions, prebuilt SD card images, guides, etc.
The variscite-bsp-platform repository contain the manifest we use for each Yocto release.
You can see that branches that have the "fsl-" prefix in their name are using the meta-fsl-bsp-release layer from NXP, and our meta-variscite-imx layer, and that branches without the "fsl-" prefix are using our meta-variscite-fslc layer.

See more info regarding our plans for the next Yocto releases here:
https://github.com/varigit/meta-variscite-imx/issues/13#issuecomment-718827712

Regards,
Eran

**Comment by floion** [comment]
Thanks @eranmati
