### ISSUE TITLE
Missing "WIFI_VSEL_GPIO" 

### ISSUE THREAD

**Issue by ghost** [varigit/meta-variscite-mx6#15]
Missing WIFI_VSEL_GPIO In connectivity-recipes for imx8mq-var-dart module(zeus 5.4.x), which prevents wifi from starting. After manually adding it to the script everything worked as expected.

**Comment by felixradensky** [comment]
This GPIO is now set as hog in the DTS file, see https://github.com/varigit/linux-imx/blob/imx_5.4.24_2.1.0_var01/arch/arm64/boot/dts/freescale/imx8mq-var-dart-wifi.dtsi#L13

**Comment by ghost** [comment]
Thanks, closed.
