### ISSUE TITLE
var-create-yocto-sdcard.sh not handling creating an extended SD card for fsl-image-qt5

### ISSUE THREAD

**Issue by Micrified** [varigit/meta-variscite-mx6#16]
Concerns following [step 5.3.1](https://variwiki.com/index.php?title=Yocto_Build_Release#Create_an_extended_SD_card) of the Extended SD card creation guide, when the user is building only for `fsl-image-qt5` and not `fsl-image-gui`

### Context

- **Platform**: VAR-SOM-6UL
- **Branch**: thud-fslc-4.14.78-mx6ul-v1.1
- **Image**: fsl-image-qt5

### Error 

The script `var-create-yocto-sdcard.sh` hardcodes variable: `YOCTO_DEFAULT_IMAGE` to `fsl-image-gui`, making it fail later on (after `echo "Installing Yocto Root File System:`) since it cannot find the build image `.tar.gz` expected there. This happens when the user has built for `fsl-image-qt5`. No warning or output is provided to indicate that the default image name may not be what the user intended. 

### Suggested fix

I suggest perhaps making the image to be used a required input parameter for the script

**Comment by eranmati** [comment]
Hi @Micrified.
As explained in the wiki guide, you need to build fsl-image-gui for the SD card itself, and you can build any other image for the eMMC/NAND flash, and use the "-r" parameter of the script to pick it up.

Alternatively, you can just update the YOCTO_DEFAULT_IMAGE variable in the script to use a different image for the SD card, like you did, but if you go that route then note that you need to verify that the image used has the required packages for the install_yocto.sh script (e2fsprogs, u-boot-fw-utils, etc.).
We use fsl-image-gui as the default image for the SD card itself, as it meets all of these requirements.
(Specifically for your case, fsl-image-qt5 meets these requirements too)

Regards,
Eran

**Comment by Micrified** [comment]
Wow, thank you. 

I totally missed the `-r` parameter. That's exactly what I was looking for. I'll close this issue now. 

Thanks a bunch!

**Comment by 1101101011011110** [comment]
Even using the -r parameter, I got:

`MACHINE=imx8mn-var-som`
`SD card rootfs:  fsl-image-gui-imx8mn-var-som`
`Recovery rootfs: fsl-image-qt5-imx8mn-var-som`

and then the script fails because it doesn't found fsl-image-gui-imx8mn-var-som file.

So the only solution for me was to edit the default value in the script.

**Comment by eranmati** [comment]
@1101101011011110, please see my last comment in this thread, from May 18, 2021.
"As explained in the wiki guide, you need to build fsl-image-gui for the SD card itself..."

**Comment by 1101101011011110** [comment]
@eranmati I'm just learning about yocto so maybe I'm missing something. But I did use the -r parameter with the -qt5- image. Nevertheless, the script tried to use the -gui- image for "SD card rootfs" and failed.

**Comment by eranmati** [comment]
As I explained, for using the -r parameter with another image you need to bitbake both that image (for the recovery images to be installed on the internal storage of the SOM) and the fsl-image-gui image (for the images that are installed on the SD card itself).

Anyway, changing the value of the YOCTO_DEFAULT_IMAGE variable in the script to fsl-image-qt5, like you successfully did, is fine too. This way you only need to bitbake the fsl-image-qt5 image, and it will be used for both the recovery images and for the SD card itself.
