### ISSUE TITLE
hard link to path in the var-create-yocto-sdcard.sh

### ISSUE THREAD

**Issue by Juzujka** [varigit/meta-variscite-mx6#17]
line 22: 	readonly YOCTO_BUILD=${YOCTO_ROOT}/build_xwayland
there are options, at least build_wayland

**Comment by nsdrude** [comment]
@Juzujka this repository has been split and moved to https://github.com/varigit/meta-variscite-bsp and https://github.com/varigit/meta-variscite-sdk.

There have been some improvements to the script: https://github.com/varigit/meta-variscite-sdk/blob/a827877b394db36b5ecc5b99b8e2dc1743523b72/scripts/var_mk_yocto_sdcard/var-create-yocto-sdcard.sh#L21-L40

Please move this discussion to meta-variscite-sdk if needed.
