### ISSUE TITLE
var-create-yocto-sdcard.sh: add option to use another image as base/bootable image

### ISSUE THREAD

**Issue by perezmeyer** [varigit/meta-variscite-mx6#18]
It would be really great to have an option to use a user-pecified image instead of fsl-image-gui.

**Comment by eranmati** [comment]
@perezmeyer, I'm not sure what you mean - you can use any image you want.

**Comment by perezmeyer** [comment]
My apologies, that was really really poor on my side. My bad.

What I really meant is: add an option to scripts/var_mk_yocto_sdcard/var-create-yocto-sdcard.sh to specify which image to flash into the SD card as bootable image. Note I'm not referring to the '-r' option, but the image that will be booted with the SD card itself.

**Comment by eranmati** [comment]
You can just edit the YOCTO_DEFAULT_IMAGE variable.
See:
https://github.com/varigit/meta-variscite-imx/issues/16#issuecomment-843130545

**Comment by perezmeyer** [comment]
That's exactly why I opened this issue: avoiding to edit that script (so, at least in my point of view, far from complete). To be honest the real problem here is that fsl-image-gui, while nice for demonstrations, becomes a pain to build if you don't need much of the things it builds. Having a much smaller image without all the whistles to do the job would be also just great.
