### ISSUE TITLE
ti-compat-wireless fails to build (sometimes?)

### ISSUE THREAD

**Issue by luc-tielen** [varigit/meta-variscite-mx6#3]
Hi,

I've been trying to get my own custom Linux running on the var-som-mx6. (tutorial @ http://variwiki.com/index.php?title=VAR-SOM-MX6_Yocto_Fido_R2_Build_Yocto_release)
However I have been running into some problems with ti-compat-wireless-wl18xx recipe:
- Initially I tried building core-image-minimal, since my build has to be as minimal as possible, I don't need all the qt stuff, but the build kept failing with the following error: https://gist.github.com/Primordus/7b6fb5f71db80af8d8e7966920775194
- I then tried to see if fsl-image-qt5-minimal would work as expected and build succeeded (gave around 60 warnings though). Isn't the same wifi driver also included in this image??
- After building the qt5-minimal image, I tried core-image-minimal which now also succeeded (probably since wifi driver was now already built)
- Then tried cleaning tmp and sstate-cache, ran core-image-minimal again, failed a few times (with a similar error compared to earlier), kept trying and it succeeded..

Am I doing something wrong that build is only failing sometimes? 
(Also noticed another similar issue that was resolved on this repository.., maybe related?)
I can give extra logs if you need, I really would like the build to succeed every time :)

Thanks in advance!

**Comment by varigigi** [comment]
Hi Luc,
just a couple of notes:

1) for some reason the meta-fsl-arm and meta-sdk are not aligned with official builds.
In the builld log provided I can see:
meta-fsl-arm = "imx6:2effab6c79d01062a32de4c7971bbcc38f3a760c"
meta-sdk = "imx6:6104af237f61edc2f95fb2e671d53c45617db057"
but in official builds we have
meta-fsl-arm = "(nobranch):92f95101da529f4b67ef8d1af50ce762f81f40ad"
meta-sdk = "(nobranch):1b5d466510723a4b3e4a841e6bf86915def65094"

2) the build is based on old branch imx_3.14.38_6qp-var01
could you please switch to imx_3.14.38_6qp-var02 branch and let us know?

Thanks
BR
Pier

**Comment by luc-tielen** [comment]
Hi Pier,

First of all, thanks for the quick reply!

Regarding your notes: 
1) = OK I think, the tutorial at http://variwiki.com/index.php?title=VAR-SOM-MX6_Yocto_Fido_R2_Build_Yocto_release#Setup_and_build_Yocto_QT5.2FX in step 3 and 4 does some things which update EULA etc, small patches, ... I made 1 commit in each repo (in case more changes have to be added in the future), the parent commit of each submodule/yocto layer matches with the hashes you posted so I think this is fine..

2) http://variwiki.com/index.php?title=VAR-SOM-MX6_Yocto_Fido_R2_Build_Yocto_release#Setup_and_build_Yocto_QT5.2FX also suggested to checkout branch var01, checking out var02 seems to work! 

FYI: I still get 1 warning when building (but for the rest build seems to work fine so I can move on for now :smile:):
"WARNING: ~/yocto/build/tmp/work/var_som_mx6-poky-linux-gnueabi/ti-compat-wireless-wl18xx/R8.6_SP1-r0/compat-wireless ('S') doesn't exist, please set 'S' to a proper value"

Conclusion: the guide I followed is probably outdated, I will let somebody know to update which git branch they should check out..
Thanks very much!

Kind regards,
Luc

**Comment by varigigi** [comment]
Hi Luc,
thanks for your feedback!
Just for now ;) I will close the issue, but feel free to get back.

BR
Pier
