### ISSUE TITLE
Missing commit for linux-variscite upstream

### ISSUE THREAD

**Issue by luc-tielen** [varigit/meta-variscite-mx6#4]
Hi,

I'm currently working on imx6q and tried out the new 4.1.15 branch.
I noticed after commit f05e15f4cdd232b954294f50f9d03361a64b8335, yocto can't build an image anymore.
I get the following error:

ERROR: Fetcher failure: Unable to find revision 5aad9684dde014d47c8c940684ad4b849009395c in branch imx-rel_imx_4.1.15_1.1.0_ga-VAR01-beta even from upstream
ERROR: Function failed: Fetcher failure for URL: 'git://github.com/varigit/linux-2.6-imx.git;protocol=git;branch=imx-rel_imx_4.1.15_1.1.0_ga-VAR01-beta'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: ~/yocto/build/tmp/work/var_som_mx6-poky-linux-gnueabi/linux-variscite/4.1.15-r0/temp/log.do_fetch.13640
ERROR: Task 45 (~/yocto/sources/meta-variscite-mx6/recipes-kernel/linux/linux-variscite_4.1.15.bb, do_fetch) failed with exit code '1'

I think a commit is missing in linux-2.6-imx repository that actually includes the bluetooth fix.
Reverting the last commit fixes it now for me.
Could somebody look into this? Thanks in advance :smile:.

Kind regards,

Luc

**Comment by eranmati** [comment]
Hi Luc.
It should be fixed now.

Regards,
Eran

On Mon, Apr 25, 2016 at 10:16 AM, Primordus notifications@github.com
wrote:

> Hi,
> 
> I'm currently working on imx6q and tried out the new 4.1.15 branch.
> I noticed after commit f05e15f
> https://github.com/varigit/meta-variscite-mx6/commit/f05e15f4cdd232b954294f50f9d03361a64b8335,
> yocto can't build an image anymore.
> I get the following error:
> 
> ERROR: Fetcher failure: Unable to find revision
> 5aad9684dde014d47c8c940684ad4b849009395c in branch
> imx-rel_imx_4.1.15_1.1.0_ga-VAR01-beta even from upstream
> ERROR: Function failed: Fetcher failure for URL: 'git://
> github.com/varigit/linux-2.6-imx.git;protocol=git;branch=imx-rel_imx_4.1.15_1.1.0_ga-VAR01-beta'.
> Unable to fetch URL from any source.
> ERROR: Logfile of failure stored in:
> ~/yocto/build/tmp/work/var_som_mx6-poky-linux-gnueabi/linux-variscite/4.1.15-r0/temp/log.do_fetch.13640
> ERROR: Task 45 (~/yocto/sources/meta-variscite-mx6/recipes-kernel/linux/
> linux-variscite_4.1.15.bb, do_fetch) failed with exit code '1'
> 
> I think a commit is missing in linux-2.6-imx repository that actually
> includes the bluetooth fix.
> Reverting the last commit fixes it now for me.
> Could somebody look into this? Thanks in advance [image: :smile:].
> 
> Kind regards,
> 
> Luc
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/varigit/meta-variscite-mx6/issues/4

##

**Comment by luc-tielen** [comment]
Hi Eran,

Just verified it, it works now!
Thanks for quick response, much appreciated!

Kind regards,
Luc
