### ISSUE TITLE
How to get a Yocto build for the DART-MX8M?

### ISSUE THREAD

**Issue by graugans** [varigit/meta-variscite-mx6#6]
The only reference I found is this branch ``morty-imx-4.9.51-var01`` I tried the following bblayers set-up:
```
BBLAYERS = " \
  ${BSPDIR}/sources/poky/meta \
  ${BSPDIR}/sources/poky/meta-poky \
  \
  ${BSPDIR}/sources/meta-openembedded/meta-oe \
  ${BSPDIR}/sources/meta-openembedded/meta-multimedia \
  ${BSPDIR}/sources/meta-openembedded/meta-python \
  \
  ${BSPDIR}/sources/meta-swupdate \
  \
  ${BSPDIR}/sources/meta-freescale \
  ${BSPDIR}/sources/meta-freescale-distro \
  \
  ${BSPDIR}/sources/meta-qt5 \
  \
  ${BSPDIR}/sources/meta-variscite-fslc \
  ${BSPDIR}/sources/meta-variscite-imx \
  \
  ${BSPDIR}/sources/meta-walnut \
  \
"
```
So all of the branches are based on ``morty`` the ``meta-walnut`` is my branch which more or less adds a image and some bbappends. It looks like the ``morty`` branch of ``meta-freescale`` is missing some recipes which you are using ``.bbappends`` for. So in a naive approach I put those in my ``meta-walnut`` which solved the missing base recipe issue. Nevertheless I do feel like I am doing something unintended.  I am posting here because I can not find any category for mx8m boards on your forum.

**Comment by eranmati** [comment]
Hi Christian.
Please see:
http://variwiki.com/index.php?title=DART-MX8M
http://variwiki.com/index.php?title=Yocto_Build_Release&release=RELEASE_MORTY_V1.4_DART-MX8M

Regards,
Eran

**Comment by graugans** [comment]
@eranmati thank you very much, looks like I have overlooked it. I guess You do not have much influence on NXP but having those ``git://`` URLs in the manifest makes it impossible to clone this behind a cooperate Proxy. I can fix this but it is inconvenient.

**Comment by eranmati** [comment]
Note that Yocto extensively uses remote git repositories, also when bitbaking.
You should set up your firewall to allow it.

**Comment by graugans** [comment]
@eranmati this is why the ``MIRRORS`` variable comes in handy.

```
MIRRORS += "\
    git://anongit.freedesktop.org/.*     git://anongit.freedesktop.org/git/PATH;protocol=https \n \
"
```
